apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-dp
  labels:
    app: bank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app : bank
    spec:
      containers:
        - name: cont1
          image: raghuraj081/mb-img:latest
